export const authConstants = {
    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGIN_FAILURE:'LOGIN_FAILURE',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGOUT_REQUEST:'LOGOUT_REQUEST'
}

export const CategoryConstants = {
    GET_ALL_CATEGORIES_REQUEST:'GET_ALL_CATEGORIES_REQUEST',
    GET_ALL_CATEGORIES_FAILURE:'GET_ALL_CATEGORIES_FAILURE',
    GET_ALL_CATEGORIES_SUCCESS:'GET_ALL_CATEGORIES_SUCCESS',
    ADD_NEW_CATEGORY_REQUEST:'ADD_NEW_CATEGORY_REQUEST',
    ADD_NEW_CATEGORY_SUCCESS:'ADD_NEW_CATEGORY_SUCCESS',
    ADD_NEW_CATEGORY_FAILURE:'ADD_NEW_CATEGORY_FAILURE',
}


export const ProductConstants = {
    GET_PRODUCT_BY_SLUG_REQUEST:'GET_PRODUCT_BY_SLUG_REQUEST',
    GET_PRODUCT_BY_SLUG_FAILURE:'GET_PRODUCT_BY_SLUG_FAILURE',
    GET_PRODUCT_BY_SLUG_SUCCESS:'GET_PRODUCT_BY_SLUG_SUCCESS'
}
