export const authConstants = {
    LOGIN_REQUEST:'LOGIN_REQUEST',
    LOGIN_FAILURE:'LOGIN_FAILURE',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',
    LOGOUT_REQUEST:'LOGOUT_REQUEST'
}

export const CategoryConstants = {
    GET_ALL_CATEGORIES_REQUEST:'GET_ALL_CATEGORIES_REQUEST',
    GET_ALL_CATEGORIES_FAILURE:'GET_ALL_CATEGORIES_FAILURE',
    GET_ALL_CATEGORIES_SUCCESS:'GET_ALL_CATEGORIES_SUCCESS',
    ADD_NEW_CATEGORY_REQUEST:'ADD_NEW_CATEGORY_REQUEST',
    ADD_NEW_CATEGORY_SUCCESS:'ADD_NEW_CATEGORY_SUCCESS',
    ADD_NEW_CATEGORY_FAILURE:'ADD_NEW_CATEGORY_FAILURE',
}


export const ProductConstants = {
    GET_ALL_PRODUCT_REQUEST:'GET_ALL_PRODUCT_REQUEST',
    GET_ALL_PRODUCT_FAILURE:'GET_ALL_PRODUCT_FAILURE',
    GET_ALL_PRODUCT_SUCCESS:'GET_ALL_PRODUCT_SUCCESS',
    ADD_NEW_PRODUCT_REQUEST:'ADD_NEW_PRODUCT_REQUEST',
    ADD_NEW_PRODUCT_SUCCESS:'ADD_NEW_PRODUCT_SUCCESS',
    ADD_NEW_PRODUCT_FAILURE:'ADD_NEW_PRODUCT_FAILURE', 
}

export const InitialDataConstants = {
    GET_INTITIAL_DATA_REQUEST:'GET_INTITIAL_DATA_REQUEST',
    GET_INTITIAL_DATA_FAILURE:'GET_INTITIAL_DATA_FAILURE',
    GET_INTITIAL_DATA_SUCCESS:'GET_INTITIAL_DATA_SUCCESS'
}